modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/lucianowayand/eyes-of-ice-and-fire/issues" #optional

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/lucianowayand/eyes-of-ice-and-fire"
logoFile="logo.png"
credits="Thanks to MKuckert for the original mod."
authors="${mod_authors}"
description='''${mod_description}'''