modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/lucianowayand/eyes-of-ice-and-fire/issues" #optional

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="logo.png"
credits="Thanks to MKuckert for the original mod."
authors="${mod_authors}"
description='''${mod_description}'''